id: I759EED98
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:19:06+00:00'
last_modified: '2022-06-07T17:29:58.849033+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016795
  title: དཔལ་ལྡན་ཀརྨ་པ་ཆེན་པོ་རྗེ་བཙུན་ཆོས་དབྱིངས་རྡོ་རྗེའི་རྣམ་པར་ཐར་པ་དད་པའི་དགའ་སྟོན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9FB8:
      image_group_id: I01CT1757
      title: ''
      total_pages: 28
      order: 1
      base_file: 9FB8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
