id: P003091
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:39:47.146221
source_metadata:
  id: bdr:W00EGS1016795
  title: དཔལ་ལྡན་ཀརྨ་པ་ཆེན་པོ་རྗེ་བཙུན་ཆོས་དབྱིངས་རྡོ་རྗེའི་རྣམ་པར་ཐར་པ་དད་པའི་དགའ་སྟོན
  author: ''
  volumes:
    9b9ec000a7624e7b81d515e91839a76c:
      image_group_id: I01CT1757
      title: ''
      volume_number: 1
      total_pages: 28
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
